# Generated by Django 2.2.22 on 2022-07-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('cname', models.CharField(max_length=100)),
                ('cdate', models.DateField()),
                ('cby', models.CharField(max_length=100)),
            ],
        ),
    ]
